apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-atscale-logs
spec:
  storageClassName: {{.Values.storageData.storageClass}}
  #volumeName: pv-atscale-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storageData.size}}