{{- if eq (toString .Values.designer.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: atscale-svc
spec:
  type: ClusterIP
  ports:
    - port: 11111
      targetPort: 11111
      name: atscalejdbcport
    - port: 10502
      targetPort: 10502
      name: atscalemdxport
  selector:
    {{- include "atscale.selectorLabels" . | nindent 4 }}
{{- end }}